<a href="https://colab.research.google.com/github/kailashchaudhary-p/Data-Science-Learning/blob/main/Pandas/chapter%201/Untitled.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import pandas as pd

In [58]:
s=pd.Series([10,20,30,40,50])
s

,0
0,10
1,20
2,30
3,40
4,50


In [59]:
s.dtype
s.index
s.values

array([10, 20, 30, 40, 50])

In [60]:
s.name='numbers'
print(s.name)

numbers


In [61]:
#indexing
s[0]
s[0:1:4]

,numbers
0,10


In [62]:
s[3:0]

,numbers


In [63]:
#ilock--> location based index
s.iloc[3]
s.iloc[[1,3,4]]

,numbers
1,20
3,40
4,50


In [64]:
#now we will change our indexing for perr=ticular usage
index=['apple','banana','grapes','orange','mango']
s.index=index



In [65]:
s.loc['apple']

np.int64(10)

In [66]:
s2={
    'apple':0.7,
    'banana':0.6,
    'grapes':3.0,
    'avacado':1.0,
    'mango':0.9,
    'cheeri':0.8,
    'kiwi':1.1,
    'orange':2.5,
    'blackberries':2.3
}
s2

{'apple': 0.7,
 'banana': 0.6,
 'grapes': 3.0,
 'avacado': 1.0,
 'mango': 0.9,
 'cheeri': 0.8,
 'kiwi': 1.1,
 'orange': 2.5,
 'blackberries': 2.3}

In [67]:
s2=pd.Series(s2)
s2

,0
apple,0.7
banana,0.6
grapes,3.0
avacado,1.0
mango,0.9
cheeri,0.8
kiwi,1.1
orange,2.5
blackberries,2.3


In [68]:
print(type(s2))

<class 'pandas.core.series.Series'>


In [69]:
s2.unique()

array([0.7, 0.6, 3. , 1. , 0.9, 0.8, 1.1, 2.5, 2.3])

In [70]:
s2.count()

np.int64(9)

In [71]:
s2.describe()

,0
count,9.000000
mean,1.433333
std,0.905539
min,0.600000
25%,0.800000
50%,1.000000
75%,2.300000
max,3.000000


In [72]:
#Logic oprator


In [73]:
#Data Frame (df)
data={
    'name':['kailash','ajay','aman','alice','bob','charlie'],
    'age':[20,25,30,35,19,22],
    'Department':['IT','HR','Finance','IT','HR','Finance'],
    'salary':[50000,60000,40000,250000,300000,80000]
}
data

{'name': ['kailash', 'ajay', 'aman', 'alice', 'bob', 'charlie'],
 'age': [20, 25, 30, 35, 19, 22],
 'Department': ['IT', 'HR', 'Finance', 'IT', 'HR', 'Finance'],
 'salary': [50000, 60000, 40000, 250000, 300000, 80000]}

In [74]:
df=pd.DataFrame(data)

In [75]:
df

,name,age,Department,salary
0,kailash,20,IT,50000
1,ajay,25,HR,60000
2,aman,30,Finance,40000
3,alice,35,IT,250000
4,bob,19,HR,300000
5,charlie,22,Finance,80000


In [76]:
df.head(2)


,name,age,Department,salary
0,kailash,20,IT,50000
1,ajay,25,HR,60000


In [77]:
df.tail(5)

,name,age,Department,salary
1,ajay,25,HR,60000
2,aman,30,Finance,40000
3,alice,35,IT,250000
4,bob,19,HR,300000
5,charlie,22,Finance,80000


In [78]:
#loc&iloc in df

In [79]:
df.loc[1:3]


,name,age,Department,salary
1,ajay,25,HR,60000
2,aman,30,Finance,40000
3,alice,35,IT,250000


In [80]:
df.iloc[1:3,[1,3
             ]]

,age,salary
1,25,60000
2,30,40000


In [81]:
#the direct indexing is in data frame or series is very comlex thats why we will use loc or iloc

In [82]:
#to se perticuler column or multiple
df.age

,age
0,20
1,25
2,30
3,35
4,19
5,22


In [83]:
df['age']

,age
0,20
1,25
2,30
3,35
4,19
5,22


In [86]:
df['age'].unique(

)

array([20, 25, 30, 35, 19, 22])

In [87]:
df.describe()

,age,salary
count,6.000000,6.000000
mean,25.166667,130000.000000
std,6.242329,114192.819389
min,19.000000,40000.000000
25%,20.500000,52500.000000
50%,23.500000,70000.000000
75%,28.750000,207500.000000
max,35.000000,300000.000000
