<a href="https://colab.research.google.com/github/kailashchaudhary-p/Data-Science-Learning/blob/main/Pandas/chapter%201/Untitled.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
s=pd.Series([10,20,30,40,50])
s

,0
0,10
1,20
2,30
3,40
4,50


In [3]:
s.dtype
s.index
s.values

array([10, 20, 30, 40, 50])

In [4]:
s.name='numbers'
print(s.name)

numbers


In [5]:
#indexing
s[0]
s[0:1:4]

,numbers
0,10


In [6]:
s[3:0]

,numbers


In [7]:
#ilock--> location based index
s.iloc[3]
s.iloc[[1,3,4]]

,numbers
1,20
3,40
4,50


In [8]:
#now we will change our indexing for perr=ticular usage
index=['apple','banana','grapes','orange','mango']
s.index=index



In [9]:
s.loc['apple']

np.int64(10)

In [10]:
s2={
    'apple':0.7,
    'banana':0.6,
    'grapes':3.0,
    'avacado':1.0,
    'mango':0.9,
    'cheeri':0.8,
    'kiwi':1.1,
    'orange':2.5,
    'blackberries':2.3
}
s2

{'apple': 0.7,
 'banana': 0.6,
 'grapes': 3.0,
 'avacado': 1.0,
 'mango': 0.9,
 'cheeri': 0.8,
 'kiwi': 1.1,
 'orange': 2.5,
 'blackberries': 2.3}

In [11]:
s2=pd.Series(s2)
s2

,0
apple,0.7
banana,0.6
grapes,3.0
avacado,1.0
mango,0.9
cheeri,0.8
kiwi,1.1
orange,2.5
blackberries,2.3


In [12]:
print(type(s2))

<class 'pandas.core.series.Series'>


In [13]:
s2.unique()

array([0.7, 0.6, 3. , 1. , 0.9, 0.8, 1.1, 2.5, 2.3])

In [14]:
s2.count()

np.int64(9)

In [15]:
s2.describe()

,0
count,9.000000
mean,1.433333
std,0.905539
min,0.600000
25%,0.800000
50%,1.000000
75%,2.300000
max,3.000000


In [16]:
#Logic oprator


In [17]:
#Data Frame (df)
data={
    'name':['kailash','ajay','aman','alice','bob','charlie'],
    'age':[20,25,30,35,19,22],
    'Department':['IT','HR','Finance','IT','HR','Finance'],
    'salary':[50000,60000,40000,250000,300000,80000]
}
data

{'name': ['kailash', 'ajay', 'aman', 'alice', 'bob', 'charlie'],
 'age': [20, 25, 30, 35, 19, 22],
 'Department': ['IT', 'HR', 'Finance', 'IT', 'HR', 'Finance'],
 'salary': [50000, 60000, 40000, 250000, 300000, 80000]}

In [18]:
df=pd.DataFrame(data)

In [19]:
df

,name,age,Department,salary
0,kailash,20,IT,50000
1,ajay,25,HR,60000
2,aman,30,Finance,40000
3,alice,35,IT,250000
4,bob,19,HR,300000
5,charlie,22,Finance,80000


In [20]:
df.head(2)


,name,age,Department,salary
0,kailash,20,IT,50000
1,ajay,25,HR,60000


In [21]:
df.tail(5)

,name,age,Department,salary
1,ajay,25,HR,60000
2,aman,30,Finance,40000
3,alice,35,IT,250000
4,bob,19,HR,300000
5,charlie,22,Finance,80000


In [22]:
#loc&iloc in df

In [23]:
df.loc[1:3]


,name,age,Department,salary
1,ajay,25,HR,60000
2,aman,30,Finance,40000
3,alice,35,IT,250000


In [24]:
df.iloc[1:3,[1,3
             ]]

,age,salary
1,25,60000
2,30,40000


In [25]:
#the direct indexing is in data frame or series is very comlex thats why we will use loc or iloc

In [26]:
#to se perticuler column or multiple
df.age

,age
0,20
1,25
2,30
3,35
4,19
5,22


In [27]:
df['age']

,age
0,20
1,25
2,30
3,35
4,19
5,22


In [28]:
df['age'].unique(

)

array([20, 25, 30, 35, 19, 22])

In [29]:
df.describe()

,age,salary
count,6.000000,6.000000
mean,25.166667,130000.000000
std,6.242329,114192.819389
min,19.000000,40000.000000
25%,20.500000,52500.000000
50%,23.500000,70000.000000
75%,28.750000,207500.000000
max,35.000000,300000.000000


In [30]:
df.rename(columns={'name':'Name'},inplace=True)

In [31]:
df

,Name,age,Department,salary
0,kailash,20,IT,50000
1,ajay,25,HR,60000
2,aman,30,Finance,40000
3,alice,35,IT,250000
4,bob,19,HR,300000
5,charlie,22,Finance,80000


In [32]:
#broadcasting in pandas
df['salary']=df['salary']+5000

In [33]:
df

,Name,age,Department,salary
0,kailash,20,IT,55000
1,ajay,25,HR,65000
2,aman,30,Finance,45000
3,alice,35,IT,255000
4,bob,19,HR,305000
5,charlie,22,Finance,85000


In [34]:
df.drop(columns=['salary'],inplace=True)

In [35]:
import numpy as np
dataset={
    'name':['kailash','ajay',np.nan,'aman','alice','bob',np.nan,'charlie',np.nan],
    'urn':[789,123,456,741,np.nan,963,852,np.nan,951],
    'project':['banking app','task managment','clone spotify','card managment',np.nan,'player','xyz','abc','k']
}
df2=pd.DataFrame(dataset)

In [36]:
df2

,name,urn,project
0,kailash,789.0,banking app
1,ajay,123.0,task managment
2,NaN,456.0,clone spotify
3,aman,741.0,card managment
4,alice,NaN,NaN
5,bob,963.0,player
6,NaN,852.0,xyz
7,charlie,NaN,abc
8,NaN,951.0,k


In [37]:
#now this is our prectice set in this we work on df2 data opration and we clean the data
df2.isnull().sum()


,0
name,3
urn,2
project,1


In [38]:
df2.dropna()

,name,urn,project
0,kailash,789.0,banking app
1,ajay,123.0,task managment
3,aman,741.0,card managment
5,bob,963.0,player


In [39]:
df2.dropna(how='all')

,name,urn,project
0,kailash,789.0,banking app
1,ajay,123.0,task managment
2,NaN,456.0,clone spotify
3,aman,741.0,card managment
4,alice,NaN,NaN
5,bob,963.0,player
6,NaN,852.0,xyz
7,charlie,NaN,abc
8,NaN,951.0,k


In [40]:
df2.dropna(how='any')

,name,urn,project
0,kailash,789.0,banking app
1,ajay,123.0,task managment
3,aman,741.0,card managment
5,bob,963.0,player


In [41]:
#this the other way fill the null values
df2.fillna(5)

,name,urn,project
0,kailash,789.0,banking app
1,ajay,123.0,task managment
2,5,456.0,clone spotify
3,aman,741.0,card managment
4,alice,5.0,5
5,bob,963.0,player
6,5,852.0,xyz
7,charlie,5.0,abc
8,5,951.0,k


In [42]:
df

,Name,age,Department
0,kailash,20,IT
1,ajay,25,HR
2,aman,30,Finance
3,alice,35,IT
4,bob,19,HR
5,charlie,22,Finance


In [43]:
df2

,name,urn,project
0,kailash,789.0,banking app
1,ajay,123.0,task managment
2,NaN,456.0,clone spotify
3,aman,741.0,card managment
4,alice,NaN,NaN
5,bob,963.0,player
6,NaN,852.0,xyz
7,charlie,NaN,abc
8,NaN,951.0,k


In [44]:
df2['urn'].fillna(df2['urn'].median())

,urn
0,789.0
1,123.0
2,456.0
3,741.0
4,789.0
5,963.0
6,852.0
7,789.0
8,951.0


In [45]:
#now we will know about the forward fill & backword fill
#the forword fill is top to bottum & the backword fill is bottom to top
df2['urn'].fillna(method='ffill')

/tmp/ipykernel_3455/880483959.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2['urn'].fillna(method='ffill')


,urn
0,789.0
1,123.0
2,456.0
3,741.0
4,741.0
5,963.0
6,852.0
7,852.0
8,951.0


In [46]:
df2['urn'].fillna(method='bfill')

/tmp/ipykernel_3455/489831362.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2['urn'].fillna(method='bfill')


,urn
0,789.0
1,123.0
2,456.0
3,741.0
4,963.0
5,963.0
6,852.0
7,951.0
8,951.0


In [47]:
#now we will replace the value
df2['name']=df2['name'].replace('kailash','harsh')
df2

,name,urn,project
0,harsh,789.0,banking app
1,ajay,123.0,task managment
2,NaN,456.0,clone spotify
3,aman,741.0,card managment
4,alice,NaN,NaN
5,bob,963.0,player
6,NaN,852.0,xyz
7,charlie,NaN,abc
8,NaN,951.0,k


In [48]:
df2

,name,urn,project
0,harsh,789.0,banking app
1,ajay,123.0,task managment
2,NaN,456.0,clone spotify
3,aman,741.0,card managment
4,alice,NaN,NaN
5,bob,963.0,player
6,NaN,852.0,xyz
7,charlie,NaN,abc
8,NaN,951.0,k


In [49]:
#now we will deal with duplicate values
df_dup=df2.duplicated()
df_dup

,0
0,False
1,False
2,False
3,False
4,False
5,False
6,False
7,False
8,False


In [49]:
#now we will learn about the lamda function in pandas