<a href="https://colab.research.google.com/github/kailashchaudhary-p/Data-Science-Learning/blob/main/Pandas/chapter%201/Untitled.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import pandas as pd

In [37]:
s=pd.Series([10,20,30,40,50])
s

,0
0,10
1,20
2,30
3,40
4,50


In [38]:
s.dtype
s.index
s.values

array([10, 20, 30, 40, 50])

In [39]:
s.name='numbers'
print(s.name)

numbers


In [40]:
#indexing
s[0]
s[0:1:4]

,numbers
0,10


In [41]:
s[3:0]

,numbers


In [42]:
#ilock--> location based index
s.iloc[3]
s.iloc[[1,3,4]]

,numbers
1,20
3,40
4,50


In [43]:
#now we will change our indexing for perr=ticular usage
index=['apple','banana','grapes','orange','mango']
s.index=index



In [44]:
s.loc['apple']

np.int64(10)

In [45]:
s2={
    'apple':0.7,
    'banana':0.6,
    'grapes':3.0,
    'avacado':1.0,
    'mango':0.9,
    'cheeri':0.8,
    'kiwi':1.1,
    'orange':2.5,
    'blackberries':2.3
}
s2

{'apple': 0.7,
 'banana': 0.6,
 'grapes': 3.0,
 'avacado': 1.0,
 'mango': 0.9,
 'cheeri': 0.8,
 'kiwi': 1.1,
 'orange': 2.5,
 'blackberries': 2.3}

In [46]:
s2=pd.Series(s2)
s2

,0
apple,0.7
banana,0.6
grapes,3.0
avacado,1.0
mango,0.9
cheeri,0.8
kiwi,1.1
orange,2.5
blackberries,2.3


In [47]:
print(type(s2))

<class 'pandas.core.series.Series'>


In [48]:
s2.unique()

array([0.7, 0.6, 3. , 1. , 0.9, 0.8, 1.1, 2.5, 2.3])

In [49]:
s2.count()

np.int64(9)

In [50]:
s2.describe()

,0
count,9.000000
mean,1.433333
std,0.905539
min,0.600000
25%,0.800000
50%,1.000000
75%,2.300000
max,3.000000


In [51]:
#Logic oprator


In [52]:
#Data Frame (df)
data={
    'name':['kailash','ajay','aman','alice','bob','charlie'],
    'age':[20,25,30,35,19,22],
    'Department':['IT','HR','Finance','IT','HR','Finance'],
    'salary':[50000,60000,40000,250000,300000,80000]
}
data

{'name': ['kailash', 'ajay', 'aman', 'alice', 'bob', 'charlie'],
 'age': [20, 25, 30, 35, 19, 22],
 'Department': ['IT', 'HR', 'Finance', 'IT', 'HR', 'Finance'],
 'salary': [50000, 60000, 40000, 250000, 300000, 80000]}

In [53]:
df=pd.DataFrame(data)

In [54]:
df

,name,age,Department,salary
0,kailash,20,IT,50000
1,ajay,25,HR,60000
2,aman,30,Finance,40000
3,alice,35,IT,250000
4,bob,19,HR,300000
5,charlie,22,Finance,80000


In [55]:
df.head(2)


,name,age,Department,salary
0,kailash,20,IT,50000
1,ajay,25,HR,60000


In [56]:
df.tail(5)

,name,age,Department,salary
1,ajay,25,HR,60000
2,aman,30,Finance,40000
3,alice,35,IT,250000
4,bob,19,HR,300000
5,charlie,22,Finance,80000


In [57]:
#loc&iloc in df

In [58]:
df.loc[1:3]


,name,age,Department,salary
1,ajay,25,HR,60000
2,aman,30,Finance,40000
3,alice,35,IT,250000


In [59]:
df.iloc[1:3,[1,3
             ]]

,age,salary
1,25,60000
2,30,40000


In [60]:
#the direct indexing is in data frame or series is very comlex thats why we will use loc or iloc

In [61]:
#to se perticuler column or multiple
df.age

,age
0,20
1,25
2,30
3,35
4,19
5,22


In [62]:
df['age']

,age
0,20
1,25
2,30
3,35
4,19
5,22


In [63]:
df['age'].unique(

)

array([20, 25, 30, 35, 19, 22])

In [64]:
df.describe()

,age,salary
count,6.000000,6.000000
mean,25.166667,130000.000000
std,6.242329,114192.819389
min,19.000000,40000.000000
25%,20.500000,52500.000000
50%,23.500000,70000.000000
75%,28.750000,207500.000000
max,35.000000,300000.000000


In [65]:
df.rename(columns={'name':'Name'},inplace=True)

In [66]:
df

,Name,age,Department,salary
0,kailash,20,IT,50000
1,ajay,25,HR,60000
2,aman,30,Finance,40000
3,alice,35,IT,250000
4,bob,19,HR,300000
5,charlie,22,Finance,80000


In [67]:
#broadcasting in pandas
df['salary']=df['salary']+5000

In [68]:
df

,Name,age,Department,salary
0,kailash,20,IT,55000
1,ajay,25,HR,65000
2,aman,30,Finance,45000
3,alice,35,IT,255000
4,bob,19,HR,305000
5,charlie,22,Finance,85000


In [69]:
df.drop(columns=['salary'],inplace=True)

In [74]:
import numpy as np
dataset={
    'name':['kailash','ajay',np.nan,'aman','alice','bob',np.nan,'charlie',np.nan],
    'urn':[789,123,456,741,np.nan,963,852,np.nan,951],
    'project':['banking app','task managment','clone spotify','card managment',np.nan,'player','xyz','abc','k']
}
df2=pd.DataFrame(dataset)

In [75]:
df2

,name,urn,project
0,kailash,789.0,banking app
1,ajay,123.0,task managment
2,NaN,456.0,clone spotify
3,aman,741.0,card managment
4,alice,NaN,NaN
5,bob,963.0,player
6,NaN,852.0,xyz
7,charlie,NaN,abc
8,NaN,951.0,k


In [76]:
#now this is our prectice set in this we work oin df2 data opration